---
title: "CBCL scores and LCGA analysis in ABCD"
author: "Poppy Z. Grimes"
date: "2022-12-01"
output: html_document
---

```{r}
library(car)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(haven)
library(labelled)
library(lme4)
# library(lmtest)
library(mosaic)
library(nlme)
library(purrr)
library(RNOmni)
library(stringr)
library(stringi)
library(tableone)
library(tibble)
library(tidyr)
library(mice)
library(foreign)
library(nnet)
library(reshape2)
library(tidyverse)
library(mice)
library(VIM)
```


```{r}
#need to change this to vpn store
setwd("/Users/poppygrimes/Library/CloudStorage/OneDrive-UniversityofEdinburgh/Edinburgh/gmm/gmm_abcd")


#read in from datastore using following
#select relevant variables, here using raw CBCL score
df <- read_rds('/Volumes/igmm/GenScotDepression/data/abcd/release4.0/iii.data/Mental_Health/abcd_cbcls01.rds') %>% 
  subset(select = c('src_subject_id', 'eventname', 'cbcl_scr_dsm5_depress_r', 'interview_age', 'sex'))

colnames(df) <- c("id","time","dep", "age", "sex")


df$id <- as.numeric(factor(df$id, 
                  levels=unique(df$id)))

df$age <- as.numeric(df$age)/12  #converting to years
  
df["time"][df["time"] == "baseline_year_1_arm_1"] <- "0"
df["time"][df["time"] == "1_year_follow_up_y_arm_1"] <- "1"
df["time"][df["time"] == "2_year_follow_up_y_arm_1"] <- "2"
df["time"][df["time"] == "3_year_follow_up_y_arm_1"] <- "3"

#transform(df, time = as.numeric(time), y = as.numeric(y))

i <- c(2,3)
df[ , i] <- apply(df[ , i], 2,            # Specify own function within apply
                    function(x) as.numeric(as.character(x)))


#make time and dep scores numeric and recode sex to binary 
df <- transform(df, time = as.numeric(time), 
                dep = as.numeric(dep)) %>%
                mutate(`sex` = dplyr::recode(`sex`,
                                            `M`="0",
                                            `F`="1")) 
```


```{r}
#converting dataframe to wide for MPlus input

#remove sex and age cols
dfwide <- df %>%
          subset(select = -c(4,5)) %>%
  reshape(., idvar = "id", 
                  timevar = "time", 
                  times = c("0","1","2","3"), 
                  direction = "wide") %>%
  #replace NA with numeric value for mplus that doesnt match any other
  replace(., is.na(dfwide), -9999) 


setwd('/Users/poppygrimes/Library/CloudStorage/OneDrive-UniversityofEdinburgh/Edinburgh/gmm/gmm_abcd/mplus_data')
write.table(dfwide, file = 'abcd_cbcl_wide.txt', sep = "\t",
            row.names = FALSE, col.names = FALSE)

```

```{r}
#if want to impute, inspect missing data. If not, ignore this step.

md.pattern(df)

aggr_plot <- aggr(df, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(df), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))

marginplot(df[c(1,2)])


imputed_df <- mice(df,m=5,maxit=50,meth='pmm',seed=500)
#summary(imputed_df)

imputed_df$imp$y
completed_df <- complete(imputed_df,1)

#look at imputed data
xyplot(imputed_df,y ~ ID+time,pch=18,cex=1)
#densityplot(imputed_df)
#stripplot(imputed_df, pch = 20, cex = 1.2)
#modelFit1 <- with(imputed_df,lm(y~ time+ID))
#summary(pool(modelFit1))
```

```{r}
#df=completed_df if using imputed data
#mfinds class enumeration, build ML models using that number of classes, before that need to select features 
"LCGA extension of fixed-effects growth model"

libraydep(lcmm)

#to reproduce results
set.seed(2002)

lcga1 <- hlme(dep ~ time, subject = "id", ng = 1, data = df)
lcga2 <- gridsearch(rep = 15, maxiter = 10, minit = lcga1, hlme(dep ~ time, 
                    subject = "id", ng = 2, data = df, mixture = ~ time))
lcga3 <- gridsearch(rep = 15, maxiter = 10, minit = lcga1, hlme(dep ~ time, 
                    subject = "id", ng = 3, data = df, mixture = ~ time))
lcga4 <- gridsearch(rep = 15, maxiter = 10, minit = lcga1, hlme(dep ~ time, 
                    subject = "id", ng = 4, data = df, mixture = ~ time))
lcga5 <- gridsearch(rep = 15, maxiter = 10, minit = lcga1, hlme(dep ~ time, 
                    subject = "id", ng = 5, data = df, mixture = ~ time))


summarytable(lcga1, lcga2, lcga3, lcga4, lcga5)

#address class imbalance with SMOTE if desired
```


```{r}
"GMM-2 intercepts and slopes - class specific"

set.seed(2002)

gmm1 <- hlme(dep ~ time, subject = "id", random=~1 + time, ng = 1, data = df)
gmm2 <- gridsearch(rep = 20, maxiter = 10, minit = gmm1, hlme(dep ~ time, 
                subject = "id", random=~1 + time, ng = 2, data = df, mixture = ~ time, nwg=T))
gmm3 <- gridsearch(rep = 20, maxiter = 10, minit = gmm1, hlme(dep ~ time, 
                subject = "id", random=~1+time, ng = 3, data = df, mixture = ~ time, nwg=T))
gmm4 <- gridsearch(rep = 20, maxiter = 10, minit = gmm1, hlme(dep ~ time, 
                subject = "id", random=~1+time, ng = 4, data = df, mixture = ~ time, nwg=T))
gmm5 <- gridsearch(rep = 20, maxiter = 10, minit = gmm1, hlme(dep ~ time, 
                subject = "id", random=~1+time, ng = 5, data = df, mixture = ~ time, nwg=T))


# make table with results for the 4 models:
summarytable(gmm1, gmm2, gmm3, gmm4, gmm5)
```


```{r}
#plotting, then need to assign each individual data point (individual) to a class
#plot depression score by age and then label by class and fit line

#from above choose latent class model, look at pprob, highest = class assigned to
#create new column with class assignment

id = array(lcga3$pprob$id)
class = array(lcga3$pprob$class)

new_df = data_frame(id,class)
```


```{r}
#new df with imputed values and classes labelled by their id from lcga anlaysis
#should be no missing values

data = df #or completed_df when doing imputed

labelled_data <- merge(data, new_df, by = "id")
summary(labelled_data)
```

```{r}
#plotting trajectories

ggplot(labelled_data, aes(x=age, y=dep, color=as.factor(class)))  + 
  geom_smooth() + labs(color='Trajectory', x="Age (years)", y='Depression (CBCL score)') +
  scale_color_brewer(labels = c("persistent low", "increasing", "persistent high"), palette = "Dark2")

```








